### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by iansltx** [sctr/greenrope-api-client#17]
Hi there!

Mind confirming which license this code is under? I'd like to use it on an internal project (or at least pieces of it; project is Laravel so I'll have to tweak how things get init'd) but there's no LICENSE file and composer.json says the package is proprietary, so I'm at a bit of a loss here.

Thanks!

**Comment by thomaspicquet** [comment]
@iansltx just updated the license to MIT ;)
