### ISSUE TITLE
CRM activity filtering doesn't seem to work

### ISSUE THREAD

**Issue by iansltx** [sctr/greenrope-api-client#21]
Calling

```php
$response = $crmEndpoint->getCrmActivities(['Activity' => 'Presentation']);
```

isn't filtering the collection down to that activity type. For that matter, none of the search parameters I tried entering seem to work; I get back the same (full) result set every time. What am I doing wrong?

**Comment by elizabeta-p** [comment]
The way you are sending the request always sends an empty request, therefore returning the same response. You need to pass a "query" param, and inside the query pass the needed filter params. The allowed query params are specified [here](https://github.com/sctr/greenrope-api-client/blob/master/src/Request/CrmActivity/GetCrmActivitiesRequest.php#L23).
You can use the tests as examples for what should be sent to the endpoint.

For the activity the code would look something like this: 
`$response = $crmEndpoint->getCrmActivities(['query' => ['activity' => 'Presentation']]);`

**Comment by iansltx** [comment]
Got it; thanks! Will double-check the test suite before asking other stuff that would be more obvious from looking there.
